name: Check ENV

on:
  workflow_dispatch:

jobs:
  check-the-env:
    runs-on: ubuntu-latest
    environment: env1
    steps:
    - name: echo env
      env:
        A_SECRET: ${{ secrets.A_SECRET }}
        A_ENV_VAR: ${{ vars.A_ENV_VAR }}
      run: |
        echo $A_SECRET
        echo $A_ENV_VAR

    - uses: actions/checkout@v3

    # install node
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'

    - run: export ABC=5
    - run: echo $ABC
    - run: |
        export XYZ=10
        echo $XYZ
