name: Check ENV
run-name: 1. ${{ github.head_ref }} 2. ${{ github.ref }} 3. ${{ github.ref_name }} 4. ${{ github.sha }} is running

on:
  workflow_dispatch:
  push:

jobs:
  check-the-env:
    runs-on: ubuntu-latest
    environment: env1
    steps:
    - name: echo env
      env:
        A_SECRET: ${{ secrets.A_SECRET }}
        A_ENV_VAR: ${{ vars.A_ENV_VAR }}
      run: |
        echo $A_SECRET
        echo $A_ENV_VAR

    - uses: actions/checkout@v3

    # install node
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: 'npm'

    - run: export ABC=5
    - run: echo $ABC
    - run: |
        export XYZ=10
        echo $XYZ
    - name: Generate Error Annotations
      run: |
        text="This is an Error"
        echo "::error file=app.js,line=10,col=15,title=the error title::$text"
        echo "::notice title=the notice title::Please execute the changeset manually"
        echo "::warning title=the warning title::Please execute the changeset manually"